import type { AtlasNode } from "./types";

export const ATLAS_GRAPH: AtlasNode[] = [
  {
    id: "phase1.production-unit",
    title: "Ship First Production Unit",
    kind: "MILESTONE",
    horizon: "PHASE_1",
    area: "Manufacturing",
    dependencies: ["engineering.firmware", "engineering.electronics", "manufacturing.qa", "inventory.phase1-coverage"],
    baselineCompletionPct: 0,
    weight: 10,
    status: "ACTIVE",
    estimatedHoursRemaining: 80,
    businessImpactScore: 100,
    riskScore: 70,
    href: "/"
  },
  {
    id: "phase1.customer-order",
    title: "Ship First Customer Order",
    kind: "MILESTONE",
    horizon: "PHASE_1",
    area: "Customer Validation",
    dependencies: ["phase1.production-unit", "brand.website", "operations.shipping"],
    baselineCompletionPct: 0,
    weight: 9,
    status: "ACTIVE",
    estimatedHoursRemaining: 70,
    businessImpactScore: 98,
    riskScore: 65,
    href: "/tracking"
  },
  {
    id: "phase1.first-batch",
    title: "Successfully Manufacture First Batch",
    kind: "MILESTONE",
    horizon: "PHASE_1",
    area: "Manufacturing",
    dependencies: ["manufacturing.supplier-qualification", "manufacturing.qa", "inventory.phase1-coverage"],
    baselineCompletionPct: 0,
    weight: 10,
    status: "ACTIVE",
    estimatedHoursRemaining: 100,
    businessImpactScore: 100,
    riskScore: 75,
    href: "/boms"
  },
  {
    id: "phase1.customer-experience",
    title: "Deliver Excellent Customer Experience",
    kind: "MILESTONE",
    horizon: "PHASE_1",
    area: "Operations",
    dependencies: ["operations.shipping", "brand.website", "manufacturing.qa"],
    baselineCompletionPct: 0,
    weight: 8,
    status: "ACTIVE",
    estimatedHoursRemaining: 60,
    businessImpactScore: 92,
    riskScore: 55,
    href: "/tracking"
  },
  {
    id: "engineering.firmware",
    title: "Firmware Interaction Ready",
    kind: "WORKSTREAM",
    horizon: "PHASE_1",
    area: "Firmware",
    dependencies: [],
    baselineCompletionPct: 55,
    weight: 8,
    status: "ACTIVE",
    estimatedHoursRemaining: 35,
    businessImpactScore: 95,
    riskScore: 50
  },
  {
    id: "engineering.electronics",
    title: "Electronics / PCB Ready",
    kind: "WORKSTREAM",
    horizon: "PHASE_1",
    area: "Electronics",
    dependencies: ["engineering.firmware"],
    baselineCompletionPct: 45,
    weight: 8,
    status: "ACTIVE",
    estimatedHoursRemaining: 50,
    businessImpactScore: 95,
    riskScore: 60
  },
  {
    id: "manufacturing.supplier-qualification",
    title: "Supplier Qualification",
    kind: "WORKSTREAM",
    horizon: "PHASE_1",
    area: "Supplier Communication",
    dependencies: [],
    baselineCompletionPct: 35,
    weight: 9,
    status: "ACTIVE",
    estimatedHoursRemaining: 45,
    businessImpactScore: 96,
    riskScore: 68,
    href: "/purchasing/recommendations"
  },
  {
    id: "manufacturing.qa",
    title: "QA / Test Procedure",
    kind: "WORKSTREAM",
    horizon: "PHASE_1",
    area: "Manufacturing",
    dependencies: ["engineering.electronics", "engineering.firmware"],
    baselineCompletionPct: 25,
    weight: 9,
    status: "ACTIVE",
    estimatedHoursRemaining: 60,
    businessImpactScore: 98,
    riskScore: 72,
    href: "/inventory/movements"
  },
  {
    id: "inventory.phase1-coverage",
    title: "Phase I Inventory Coverage",
    kind: "WORKSTREAM",
    horizon: "PHASE_1",
    area: "Inventory",
    dependencies: ["manufacturing.supplier-qualification"],
    baselineCompletionPct: 0,
    weight: 10,
    status: "ACTIVE",
    estimatedHoursRemaining: 30,
    businessImpactScore: 100,
    riskScore: 70,
    href: "/"
  },
  {
    id: "operations.shipping",
    title: "Shipping / Tracking Reliability",
    kind: "WORKSTREAM",
    horizon: "PHASE_1",
    area: "Operations",
    dependencies: ["manufacturing.supplier-qualification"],
    baselineCompletionPct: 30,
    weight: 7,
    status: "ACTIVE",
    estimatedHoursRemaining: 25,
    businessImpactScore: 86,
    riskScore: 45,
    href: "/tracking"
  },
  {
    id: "finance.cash-runway",
    title: "Cash Runway / Accounting Control",
    kind: "WORKSTREAM",
    horizon: "PHASE_1",
    area: "Finance",
    dependencies: [],
    baselineCompletionPct: 35,
    weight: 7,
    status: "ACTIVE",
    estimatedHoursRemaining: 25,
    businessImpactScore: 88,
    riskScore: 55,
    href: "/accounting"
  },
  {
    id: "brand.website",
    title: "Brand / Website Launch Readiness",
    kind: "WORKSTREAM",
    horizon: "PHASE_1",
    area: "Brand",
    dependencies: [],
    baselineCompletionPct: 20,
    weight: 7,
    status: "ACTIVE",
    estimatedHoursRemaining: 50,
    businessImpactScore: 90,
    riskScore: 48
  },
  {
    id: "phase2.first-50-sales",
    title: "Sell First 50 Units",
    kind: "MILESTONE",
    horizon: "PHASE_2",
    area: "Marketing",
    dependencies: ["phase1.customer-order", "phase1.customer-experience"],
    baselineCompletionPct: 0,
    weight: 7,
    status: "NOT_STARTED",
    estimatedHoursRemaining: 160,
    businessImpactScore: 92,
    riskScore: 70
  },
  {
    id: "phase2.positive-reviews",
    title: "Positive Customer Reviews",
    kind: "MILESTONE",
    horizon: "PHASE_2",
    area: "Customer Validation",
    dependencies: ["phase1.customer-experience"],
    baselineCompletionPct: 0,
    weight: 6,
    status: "NOT_STARTED",
    estimatedHoursRemaining: 90,
    businessImpactScore: 85,
    riskScore: 55
  },
  {
    id: "phase2.repeatable-production",
    title: "Repeatable Production",
    kind: "MILESTONE",
    horizon: "PHASE_2",
    area: "Manufacturing",
    dependencies: ["phase1.first-batch"],
    baselineCompletionPct: 0,
    weight: 7,
    status: "NOT_STARTED",
    estimatedHoursRemaining: 160,
    businessImpactScore: 94,
    riskScore: 70
  },
  {
    id: "phase3.scale-manufacturing",
    title: "Scale Manufacturing",
    kind: "MILESTONE",
    horizon: "PHASE_3",
    area: "Manufacturing",
    dependencies: ["phase2.repeatable-production"],
    baselineCompletionPct: 0,
    weight: 5,
    status: "NOT_STARTED",
    estimatedHoursRemaining: 300,
    businessImpactScore: 88,
    riskScore: 75
  },
  {
    id: "phase3.design-brand",
    title: "Recognizable Design Brand",
    kind: "MILESTONE",
    horizon: "PHASE_3",
    area: "Brand",
    dependencies: ["phase2.positive-reviews", "brand.website"],
    baselineCompletionPct: 0,
    weight: 5,
    status: "NOT_STARTED",
    estimatedHoursRemaining: 240,
    businessImpactScore: 82,
    riskScore: 55
  },
  {
    id: "phase4.sustainable-profitability",
    title: "Sustainable Profitability",
    kind: "MILESTONE",
    horizon: "PHASE_4",
    area: "Finance",
    dependencies: ["phase3.scale-manufacturing", "phase3.design-brand"],
    baselineCompletionPct: 0,
    weight: 4,
    status: "NOT_STARTED",
    estimatedHoursRemaining: 500,
    businessImpactScore: 100,
    riskScore: 80
  }
];

export function getAtlasSeedGraph() {
  return ATLAS_GRAPH.map((node) => ({ ...node, dependencies: [...node.dependencies] }));
}
