import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const __dirname = dirname(fileURLToPath(import.meta.url));

describe("Tracking page source contract", () => {
  it("exposes manual tracking, tracking-service refresh, linked orders, and auto refresh controls without the Alibaba capture card", () => {
    const pageSource = readFileSync(join(__dirname, "page.tsx"), "utf8");
    const actionsSource = readFileSync(join(__dirname, "actions.ts"), "utf8");
    const autoRefreshSource = readFileSync(join(__dirname, "tracking-auto-refresh.tsx"), "utf8");
    const trackingDataDisclosureSource = readFileSync(join(__dirname, "tracking-data-disclosure.tsx"), "utf8");

    expect(pageSource).toContain("Tracking Workbench");
    expect(pageSource).toContain("What Needs Attention");
    expect(pageSource).toContain("Open Shipments");
    expect(pageSource).toContain("TrackingRowCard");
    expect(pageSource).toContain("TrackingVisualCommandPanel");
    expect(pageSource).toContain("Visual Command Layer");
    expect(pageSource).toContain("Live Shipment Radar");
    expect(pageSource).toContain("Risk Spectrum");
    expect(pageSource).toContain("Provider Heartbeat");
    expect(pageSource).toContain("TrackingProviderHeartbeat");
    expect(autoRefreshSource).toContain("Actual Refresh Heartbeat");
    expect(autoRefreshSource).toContain("Provider heartbeat countdown ring");
    expect(autoRefreshSource).toContain("formatCountdown");
    expect(pageSource).toContain("Carrier Mix");
    expect(pageSource).toContain("Evidence Constellation");
    expect(pageSource).toContain("ShipmentProgressRail");
    expect(pageSource).toContain("Shipment Progress");
    expect(trackingDataDisclosureSource).toContain("Tracking Data");
    expect(pageSource).toContain("TrackingDataDisclosure");
    expect(pageSource).toContain("trackingDataReadSignature");
    expect(trackingDataDisclosureSource).toContain("Expand Tracking Data");
    expect(pageSource).toContain("Shipment Details");
    expect(pageSource).toContain("Expand Details");
    expect(trackingDataDisclosureSource).toContain("Package movements first; technical details are nested below.");
    expect(pageSource).toContain("Duplicate shipment screen: showing active stream");
    expect(pageSource).toContain("Linked Shipments");
    expect(pageSource).toContain("Raw Provider Status Payload");
    expect(pageSource).toContain("Raw Event Payloads");
    expect(pageSource).toContain("PackageTrackingDataDetails");
    expect(pageSource).toContain("EventTimeline");
    expect(pageSource).toContain("Info Received");
    expect(pageSource).toContain("Pending");
    expect(pageSource).toContain("grid-cols-5");
    expect(pageSource).toContain("Out for Delivery");
    expect(pageSource).toContain("Provider needs review before this rail can advance.");
    expect(pageSource).toContain("Add Tracking Evidence");
    expect(pageSource).toContain("No Open Tracking Issues");
    expect(pageSource).toContain("Advanced: Lead-Time Learning Audit");
    expect(pageSource).toContain("Tracking Metadata Only");
    expect(pageSource).not.toContain("Automatic Alibaba capture");
    expect(pageSource).not.toContain("Capture Alibaba tracking");
    expect(pageSource).not.toContain("captureAlibabaTrackingAction");
    expect(pageSource).not.toContain("Delivered rows are retained as history and are not polled. Carrier status remains shipment metadata only.");
    expect(pageSource).toContain("Linked Order");
    expect(pageSource).toContain("Tracking service connection");
    expect(pageSource).toContain("Recommended provider: Ship24");
    expect(pageSource).toContain("LAMBENTI_TRACKING_STATUS_AUTH_TOKEN");
    expect(pageSource).toContain("data-testid=\"tracking-row\"");
    expect(pageSource).toContain("Active tracking numbers");
    expect(pageSource).toContain("Delivered Tracking History");
    expect(pageSource).toContain("Total Ship Time");
    expect(pageSource).toContain("Advanced: Lead-Time Learning Audit");
    expect(pageSource).toContain("Reorder Forecasting Input");
    expect(pageSource).toContain("quantity ordered");
    expect(pageSource).toContain("getLeadTimeLog");
    expect(pageSource).toContain("dashboard.deliveredRows");
    expect(pageSource).toContain("refreshAllTrackingAction");
    expect(pageSource).toContain("Refresh");
    expect(pageSource).not.toContain("Refresh Due Statuses");
    expect(pageSource.indexOf("<OpenShipments rows={dashboard.rows} />")).toBeLessThan(pageSource.indexOf("<TrackingAttention dashboard={dashboard} />"));
    expect(pageSource).toContain("Manual primary");
    expect(pageSource).toContain("Catalog/default");
    expect(pageSource).toContain("completed receiving/shipping samples stay as evidence without overriding a manual value");
    expect(pageSource).not.toContain("observed weighted averages");
    expect(actionsSource).toContain("refreshAllTrackingAction");
    expect(autoRefreshSource).toContain("/api/tracking/refresh");
    expect(autoRefreshSource).toContain("x-lambenti-agent-id");
    expect(autoRefreshSource).toContain("initialNextRefreshAt");
    expect(pageSource).toContain("PendingTrackingPanel");
    expect(pageSource).toContain("No Carrier Updates Yet");
    expect(pageSource).toContain("bg-yellow-300");
    expect(pageSource).toContain("Manual Refresh Now Lives in the Provider Heartbeat Card");
    expect(autoRefreshSource).toContain("tracking-page-heartbeat");
    expect(autoRefreshSource).toContain("router.refresh");
    expect(autoRefreshSource).toContain("setInterval");
    expect(autoRefreshSource).toContain("useState<number | null>(null)");
    expect(autoRefreshSource).toContain("nowMs === null");
    expect(autoRefreshSource).not.toContain("useState(() => Date.now())");
    expect(pageSource).toContain("Fix Failed");
    expect(pageSource).toContain("Refresh Due");
    expect(pageSource).toContain("Link Evidence");
    expect(pageSource).toContain("Review Open");
    expect(pageSource).toContain("Last Good Refresh");
    expect(trackingDataDisclosureSource).toContain("lambenti:tracking-data-read-signature");
    expect(trackingDataDisclosureSource).toContain("onToggle");
    expect(trackingDataDisclosureSource).toContain("Unread");
    expect(trackingDataDisclosureSource).toContain("Reviewed");
    expect(trackingDataDisclosureSource).toContain("Expand to review");
    expect(trackingDataDisclosureSource).toContain("window.localStorage.setItem");
  });
});
