import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const __dirname = dirname(fileURLToPath(import.meta.url));

describe("Accounting workbench page", () => {
  it("exposes document drag/drop analysis and serious accounting guardrails", () => {
    const pageSource = readFileSync(join(__dirname, "page.tsx"), "utf8");
    const actionsSource = readFileSync(join(__dirname, "actions.ts"), "utf8");
    const workspaceSource = readFileSync(join(__dirname, "..", "revalidate-workspace.ts"), "utf8");
    const dropzoneSource = readFileSync(join(__dirname, "accounting-document-dropzone.tsx"), "utf8");

    expect(pageSource).toContain("Accounting Workbench");
    expect(pageSource).not.toContain("This page preserves source document evidence");
    expect(pageSource).toContain("Canadian GST/HST and Audit-Ready Records");
    expect(pageSource).toContain("source document");
    expect(pageSource).toContain("applyAccountingDocumentAction");
    expect(pageSource).toContain("attachAccountingDocumentEvidenceAction");
    expect(pageSource).toContain("Attach as Evidence");
    expect(pageSource).toContain("Attach Only — Does Not Receive Stock or Mark Paid.");
    expect(pageSource).toContain("Customer Invoices / AR");
    expect(pageSource).toContain("GL Mapping");
    expect(pageSource).toContain("Posted Journals");
    expect(pageSource).toContain('AccountingLink href="/accounting/journals" title="Posted Journals"');
    expect(pageSource).toContain('AccountingLink href="/accounting/landed-cost" title="Landed Cost"');
    expect(pageSource).toContain("data-testid={`accounting-link-");
    expect(pageSource).toContain("<a href={href}");
    expect(pageSource).toContain("Immutable evidence retained for received + open components");
    expect(pageSource).toContain("Payment Reconciliation");
    expect(pageSource).toContain("Attention Queue");
    expect(pageSource).toContain("Command Center");
    expect(pageSource).toContain("summarizeInvoiceWorkQueue");
    expect(pageSource).toContain("Invoice(s) Blocked Before Approval");
    expect(pageSource).toContain("Invoice(s) Ready for Approval");
    expect(pageSource).toContain("Only Blocker-Free Received Invoices Can Be Approved from the Queue.");
    expect(pageSource).toContain("Overdue / Due Soon");
    expect(pageSource).toContain("Bank Reconciliation");
    expect(pageSource).toContain("Posting Setup");
    expect(pageSource).toContain("Next Supplier Bills");
    expect(pageSource).toContain("Daily Bookkeeping Routine");
    expect(pageSource).toContain("getAccountingCommandCenter");
    expect(pageSource).toContain("Source Document Triage");
    expect(pageSource).toContain("href: \"#drop-source-documents\"");
    expect(pageSource).toContain("href: \"#source-document-review-queue\"");
    expect(pageSource).toContain("href=\"/accounting/accounts\"");
    expect(pageSource).toContain("href=\"/accounting/invoices\"");
    expect(pageSource).toContain("href=\"/accounting/payments\"");
    expect(pageSource).toContain("Ready to Apply");
    expect(pageSource).toContain("Needs Manual Review");
    expect(pageSource).toContain("Upload → Review → Apply/Attach → Approve/Pay → Post/Export");
    expect(pageSource.indexOf("Canadian GST/HST and Audit-Ready Records")).toBeGreaterThan(pageSource.indexOf("Uninvoiced Purchase Orders"));
    expect(pageSource.indexOf("Invoice Functionality Upgrades Active Here")).toBeGreaterThan(pageSource.indexOf("Uninvoiced Purchase Orders"));
    expect(pageSource.indexOf("Accounting Control Trail")).toBeGreaterThan(pageSource.indexOf("Uninvoiced Purchase Orders"));
    expect(pageSource).toContain("data-testid=\"accounting-document-status");
    expect(pageSource).toContain("retryAccountingDocumentExtractionAction");
    expect(pageSource).toContain("documentCanBeReanalyzed");
    expect(pageSource).toContain("Linked Evidence Is Locked After Attach/Apply");
    expect(pageSource).toContain("deleteAccountingDocumentAction");
    expect(pageSource).toContain("Delete Source Document");
    expect(pageSource).toContain("This permanently removes the saved file and analysis row");
    expect(pageSource).toContain("Paste Extracted Text / OCR and Re-Analyze");
    expect(pageSource).toContain("Save Text & Analyze");
    expect(dropzoneSource).toContain("onDrop");
    expect(dropzoneSource).toContain("useRouter");
    expect(dropzoneSource).toContain("router.refresh()");
    expect(dropzoneSource).toContain("Upload & Analyze");
    expect(dropzoneSource).toContain("Zipped Folders");
    expect(dropzoneSource).toContain(".zip");
    expect(dropzoneSource).toContain("archiveSummaries");
    expect(actionsSource).toContain("attachAccountingDocumentEvidence");
    expect(actionsSource).toContain("revalidateWorkspace");
    expect(workspaceSource).toContain("/accounting/landed-cost");
    expect(workspaceSource).toContain("/inventory/items");
    expect(workspaceSource).toContain("/inventory/valuation");
    expect(pageSource).toContain("getAttachedLandedCostEvidenceAmount");
    expect(pageSource).toContain("landed-cost evidence detected");
    expect(pageSource).toContain("Evidence Only Until Apply");
    expect(pageSource).toContain("Bookkeeping Workflow Rail");
  });
});
