import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const __dirname = dirname(fileURLToPath(import.meta.url));

describe("DashboardPage source contract", () => {
  it("renders ledger-derived in-stock quantities on the main dashboard", () => {
    const source = readFileSync(join(__dirname, "page.tsx"), "utf8");

    expect(source).toContain("In-Stock Quantities");
    expect(source).toContain("summary.stockItems");
    expect(source).toContain("Components on hand");
    expect(source).toContain("Build capacity");
    expect(source).not.toContain("bottleneck");
    expect(source).not.toContain("total BOM quantity per assembled package");
    expect(source).not.toContain("componentsRequiredPerBuild");
    expect(source).toContain("Assembled packages");
    expect(source).toContain("Ledger on-hand only; excludes");
    expect(source).toContain("Package build actions possible from already-built subassemblies and direct package inputs");
    expect(source).not.toContain("Buildable only, not assembled stock");
    expect(source).toContain("USD $");
    expect(source).not.toContain("Total available");
    expect(source).toContain("Reserved");
    expect(source).toContain("Available");
    expect(source).toContain("Phase I Launch Readiness");
    expect(source).toContain("25-unit Phase I target");
    expect(source).toContain("packageDisplayName");
    expect(source).not.toContain("LAMBENTI_PACKAGE BOM capacity");
    expect(source).toContain("subassemblies must already be ledger-built");
    expect(source).not.toContain("Phase I launch readiness");
    expect(source).not.toContain("50-package Phase I target");
    expect(source).toContain("Ready now");
    expect(source).not.toContain("A simple read-only check against");
    expect(source).not.toContain("No stock, purchasing, or accounting mutation is performed here");
    expect(source).toContain("Signals");
    expect(source).toContain("Launch Target Meter");
    expect(source).toContain("25-unit target + value mix");
    expect(source).toContain("Build Capacity by Build");
    expect(source).toContain("Buildable units by active build");
    expect(source).not.toContain("Package Bottlenecks");
    expect(source).not.toContain("buildable as subassembly");
    expect(source).not.toContain("buildableSubassemblyCapacity");
    expect(source).toContain("Stock Pressure");
    expect(source).toContain("Operations Flow");
    expect(source).toContain("Attention preview");
    expect(source).toContain("human-approval-queue");
    expect(source).not.toContain("Observed weighted avg");
    expect(source).toContain("bg-slate-950/95");
    expect(source).toContain("catalog/default");
    expect(source).toContain("Value mix");
    expect(source).toContain("summary.dashboardGraphs");
    expect(source).not.toContain("Open Next Actions");
    expect(source).not.toContain("summary.launchReadiness.nextActions.map");
    expect(source).toContain("LaunchTargetAndValueMixGraph");
    expect(source).toContain("LaunchCoverageBar");
    expect(source).toContain("Phase I material coverage gauge");
    expect(source).toContain("material covered");
    expect(source).toContain("Phase I material coverage");
    expect(source).toContain("graphs.launchCoverageSegments");
    expect(source).toContain("Built, buildable, buffer, and material-gap launch coverage");
    expect(source).not.toContain("Ready versus remaining launch gap");
    expect(source).not.toContain("Assembled means ledger on-hand");
    expect(source).not.toContain("This is material coverage, not QA/ship-ready status");
    expect(source).not.toContain("Exploded leaf-component constraint");
    expect(source).toContain("GraphNumber label=\"Built\"");
    expect(source).toContain("GraphNumber label=\"Buildable\"");
    expect(source).toContain("GraphNumber label=\"Assembly gap\"");
    expect(source).toContain("components stocked");
    expect(source).toContain("materialComponentsInStock");
    expect(source).toContain("materialComponentsRequired");
    expect(source).toContain("package-buildable");
    expect(source).toContain("CompactValuationMixGraph");
    expect(source).toContain("flex min-w-0 flex-col gap-4");
    expect(source).not.toContain("lg:grid-cols-[minmax(0,1fr)_minmax(11rem,0.72fr)]");
    expect(source.indexOf("<LaunchTargetGraph readiness={readiness} graphs={graphs} />")).toBeLessThan(
      source.indexOf("<CompactValuationMixGraph graphs={graphs} />")
    );
    expect(source).toContain("grid items-start gap-4 lg:grid-cols-2");
    expect(source).toContain("flex min-w-0 flex-col self-start rounded-xl");
    expect(source).toContain("min-w-0\">{children}");
    expect(source).not.toContain("auto-rows-fr");
    expect(source).not.toContain("flex h-full min-w-0 flex-col rounded-xl");
    expect(source).not.toContain("min-w-0 flex-1");
    expect(source).not.toContain("<GraphPanel title=\"Value mix\"");
    expect(source).not.toContain("Useful Visual Signals");
    expect(source).not.toContain("Graphs are intentionally limited");
    expect(source.indexOf("Signals")).toBeLessThan(source.indexOf("Low stock items"));
    expect(source).not.toContain("Launch Next Action");
    expect(source).not.toContain("Buildable Now");
    expect(source).toContain("Buildable now");
    expect(source).not.toContain("Unblock package build capacity");
    expect(source).toContain("formatItemType(item)");
    expect(source).toContain("formatQuantity(summary.componentsOnHand");
    expect(source).toContain("formatQuantity(item.onHand, { fixed: true })");
    expect(source).toContain("Not Currently Needed Low Stock Components");
    expect(source).toContain("summary.lowStockNotCurrentlyNeededItems");
    expect(source).toContain('GraphPanel title="Momentum Engine"');
    expect(source).toContain('GraphPanel title="Lead-Time Horizon"');
    expect(source).toContain("getFounderOsMomentum()");
    expect(source).toContain("classificationCounts");
    expect(source).toContain("Four-week work rhythm");
    expect(source).toContain("Sunday–Saturday");
    expect(source).toContain("weeklyWorkHistory");
    expect(source).toContain("weeklyHoursBarHeight");
    expect(source).toContain("Hours worked by Sunday-start week");
    expect(source).toContain("No data");
    expect(source).toContain("week.recorded");
    expect(source).toContain("This Week Worked");
    expect(source).not.toContain("Velocity without fake progress");
    expect(source.indexOf('GraphPanel title="Lead-Time Horizon"')).toBeLessThan(
      source.indexOf('GraphPanel title="Momentum Engine"')
    );
    expect(source).toContain('className="lg:col-span-2"');
  });
});
